spring:
  application:    name: eureka_config
  cloud:    config:      label: master
      server:        git:          uri: https://github.com/Sciencelyingfish/config.git
          search-paths: Spring_Cloud_Config           username: 1786410194@qq.com
          password: a19981120

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
