spring:
  application:    name: eureka_ribbon
  thymeleaf:    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:      content-type: text/html; charset=utf-8

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



